### ISSUE TITLE
{ code: 22, kind: InvalidInput, messag e: "Invalid argument" }

### ISSUE THREAD

**Issue by muziling** [lbl8603/vnts#7]
日志一直在打印
2023-12-26T09:53:45.328542162+08:00 [src/service/main_service/tcp_service.rs:26] WARN vnts::service::main_service::tcp_service:tcp accept err:Os { code: 22, kind: InvalidInput, messag
e: "Invalid argument" }

也不知道是哪里的配置有问题。

另外是否可以不生成log目录及日志，  或者加个参数禁止生成吧。

**Comment by lbl8603** [comment]
是用的哪个版本呢，日志可以通过log下的配置文件控制

**Comment by muziling** [comment]
最新的版本，带IPV6监听的。  log配置文件也会自动生成，能不能改成和客户端一样的机制，不手动创建配置yaml文件，就不生成日志。

另外 ipv6还有问题，issue里回复了，也帮忙看看

**Comment by lbl8603** [comment]
是在什么环境部署的呢

**Comment by muziling** [comment]
openwrt

**Comment by lbl8603** [comment]
前天我更新了代码，是用的最新版吗

**Comment by muziling** [comment]
就是用前天最新的， 有在监控ipv6

```
# netstat -anp|grep vnts
tcp        0      0 0.0.0.0:65534           0.0.0.0:*               LISTEN      5352/vnts
tcp        0    140 192.168.222.1:65534     59.56.145.62:4668       ESTABLISHED 5352/vnts
udp        0      0 0.0.0.0:65534           0.0.0.0:*                           5352/vnts
udp        0      0 :::65534                :::*                                5352/vnts
```

**Comment by lbl8603** [comment]
有点奇怪，能加个联系方式吗

**Comment by muziling** [comment]
QQ群里喊了

**Comment by muziling** [comment]
乌龙了，fork的commit和主线不一致
