### ISSUE TITLE
--white-toke  参数没有起作用

### ISSUE THREAD

**Issue by xieyuhua** [lbl8603/vnts#9]
./vnts --port 8004  --white-token ssdddfff
./vnt-cli -k 123456 -e 服务IP:8004

还是可以连接成功

**Comment by xieyuhua** [comment]
./vnt-cli -k 123456 -s 服务IP:8004

version 1.2.8
error:receiver error:Resource temporarily unavailable (os error 11)

是还需要开通什么端口吗？

**Comment by lbl8603** [comment]
服务端需要开UDP端口

**Comment by lbl8603** [comment]
> ./vnts --port 8004 --white-token ssdddfff ./vnt-cli -k 123456 -e 服务IP:8004
> 
> 还是可以连接成功

用自己的服务器是-s参数

**Comment by xieyuhua** [comment]
谢谢，已经可以
